- name: Accept Android SDK licenses
  run: |
    yes | sdkmanager --licenses

- name: Install Android Build Tools & Platform Tools
  run: |
    sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

- name: Build APK with Buildozer
  run: |
    buildozer android debug

